### ISSUE TITLE
Correct situation with double XML upload

### ISSUE THREAD

**Issue by dbuchwald** [dbuchwald/hacsec#40]
Scenario - go to Contacts, click on the Select file... button, open XML, click Import button. Works.
Repeat operation without reloading the page - fails. XML content sent to server is empty.
Reload page and try again - works again.

**Comment by januszsek** [comment]
The event is bind to onChange, so if You select the same file then the event will not triggered.

**Comment by dbuchwald** [comment]
Maybe we could clear the contents of the field immediately after successful upload then to ensure that onChange is correctly triggered? Or any other way to ensure that we send correct payload when sending second transaction (contactsXML is empty the second time)
